name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential libpthread-stubs0-dev libc-dev libc6-dev uuid-dev uuid libossp-uuid-dev 
    - name: Check pthread.h
      run: ls -l /usr/include/pthread.h
    - name: configure
      run: bash ./configure
    - name: make
      run: make

